export const skills = [
  { content: "Semantic HTML" },
  { content: "Responsive Web Design" },
  { content: "Working with API (fetch, axios)" },
  { content: "CSS BEM convention" },
  { content: "CSS Grid" },
  { content: "CSS Flexbox" },
  // eslint-disable-next-line
  { content: "JavaScript: ES6+" },
  { content: "TypeScript" },
  { content: "Promises, Async/Await" },
  { content: "Local Storage" },
  { content: "Error handling" },
  { content: "Markdown" },
  { content: "Immutability" },
  { content: "React" },
  { content: "React Hooks" },
  { content: "React Router" },
  { content: "Redux (Toolkit)" },
  { content: "Redux-Saga" },
  { content: "Styled-components" },
  { content: "NPM" },
  { content: "Git" },
  { content: "GitHub Pull Requests & Review" },
  { content: "Scrum" },
  { content: "Teamwork" },
];
